<legend>
    <?php if ($this->currentBranch == null): ?>
        Отрасль проекта
    <?php else: ?>
        Направление проекта для <?php echo $this->escape($this->currentBranch->title); ?>
    <?php endif; ?>
</legend>

<?php if ($this->branchId == 0): ?>
    <a href="<?php echo $this->url(array('controller' => 'project-branch', 'action' => 'add')) ?>"><i class="icon-plus"></i>Добавить отрасль</a>
<?php else: ?>
    <a href="<?php echo $this->url(array('controller' => 'project-branch', 'action' => 'add-direction')) ?>"><i class="icon-plus"></i>Добавить направление</a>
<?php endif; ?>
<br/><br/>


<table class="table table-bordered">
    <tr>
        <th>Название</th>
        <th>Действия</th>
    </tr>
    <?php if ($this->branchList != false): ?>
        <?php foreach ($this->branchList as $branch): ?>
            <tr>
                <td><a href="<?php echo $this->url(array('controller' => 'project-handbook', 'action' => 'index', 'handbook' => 'branch', 'branchId' => $branch->id)); ?>"><?php echo $this->escape($branch->title); ?></a></td>
                <td class="tedit">
                    <a href="<?php echo $this->url(array('controller' => 'project-branch', 'action' => 'edit', 'id' => $branch->id)); ?> "><i class="icon-pencil"></a>
                    <a href="<?php echo $this->url(array('controller' => 'project-branch', 'action' => 'delete', 'id' => $branch->id)); ?> " onclick="return confirmDelete('<?php $branch->title ?> ');"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($this->directionList != false): ?>
        <?php foreach ($this->directionList as $direction): ?>
            <tr>
                <td><?php echo $this->escape($direction->title); ?></a></td>
                <td class="tedit">
                    <a href="<?php echo $this->url(array('controller' => 'project-branch', 'action' => 'edit-direction', 'id' => $direction->id)); ?> "><i class="icon-pencil"></a>
                    <a href="<?php echo $this->url(array('controller' => 'project-branch', 'action' => 'delete-direction', 'id' => $direction->id)); ?> " onclick="return confirmDelete('<?php $direction->title ?> ');"><i class="icon-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>

