<legend><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Гостевая книга<?php endif; ?></legend>

<?php if (isset($this->exception_msg)): ?>
    <div class="alert alert-error">
        <h4 class="alert-heading">Ошибка!</h4>
        <?php echo $this->escape($this->exception_msg); ?>
    </div>
<?php endif; ?>

<?php if ($this->parentItem != null): ?>
    <ul class="breadcrumb">
        <li><a href="/guest-book/">Гостевая книга</a> <span class="divider">/</span></li>
        <?php if ($this->parentItem->parent !== null): ?>
            <?php if ($this->parentItem->parent->parent !== null): ?>
                <?php echo $this->partial('guest-book/_elements/breadcrumb.phtml', array('parentItem' => $this->parentItem->parent->parent)); ?>
            <?php endif; ?>
            <li><a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'index', 'parent' => $this->parentItem->parent->id)); ?>"><?php echo $this->escape($this->parentItem->parent->getTitle()); ?></a> <span class="divider">/</span></li>
        <?php endif; ?>
        <li class="active"><?php echo $this->escape($this->parentItem->title); ?></li>
    </ul>
<?php endif; ?>

<a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'add')) ?>"><i class="icon-plus"></i>Добавить страницу</a><br/><br/>

<?php if (isset($this->breadcrumbs)): ?>
    <a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'index', 'parent' => 0)); ?>">/..</a>
    <?php if (!empty($this->breadcrumbs)): ?>
        &nbsp;/
        <?php foreach ($this->breadcrumbs as $crumb): ?>
            <a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'index', 'parent' => $crumb->id)); ?>"><?php echo $this->escape($crumb->title); ?></a>&nbsp;/
        <?php endforeach; ?>
    <?php endif; ?>
    <br/><br/>
<?php endif; ?>

<div class="sub-menu">
    <img src="/images/add.png"/>&nbsp;<a href="/guest-book/addfolder/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">добавить папку</a>&nbsp;&nbsp;
    <img src="/images/add.png"/>&nbsp;<a href="/guest-book/add/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">добавить документ</a>
</div>

<table width="100%">
    <tr>
        <td class="ttovar">Название</td>
        <td class="ttovar"></td>
    </tr>

    <?php if ($this->guest - bookFolderList !== false): ?>
        <?php foreach ($this->documentFolderList as $item): ?>
            <tr>
                <td class="ttovar">
                    <img src="/images/folder.png"/>&nbsp;
                    <a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'index', 'parent' => $item->id)); ?>"><?php echo $this->escape($item->title); ?></a></td>
                <td class="tedit">
                    <img src="/images/edit.png"/>&nbsp;<a href="/guest-book/editfolder/id/<?php echo $item->id; ?>/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">редактировать</a><br/>
                    <img src="/images/delete.png"/>&nbsp;<a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'deletefolder', 'id' => $item->id)) ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');" style="color: #830000">удалить</a></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($this->documentList !== false): ?>
        <?php foreach ($this->documentList as $item): ?>
            <tr>
                <td class="ttovar"><img src="/images/document.png"/>&nbsp;<?php echo $this->escape($item->title); ?></td>
                <td class="tedit">
                    <img src="/images/edit.png"/>&nbsp;<a href="/guest-book/edit/id/<?php echo $item->id; ?>/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">редактировать</a><br/>
                    <img src="/images/delete.png"/>&nbsp;<a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'delete', 'id' => $item->id)) ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');" style="color: #830000">удалить</a></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>