<div class="right">
    <ul class="secand_menu">
        <li>
            <a href="/">ИЗБРАННОЕ</a>
            <ul>
                <li><a href="/">Рекомендуемые</a></li>
                <li><a href="/">Популярные</a></li>
                <li><a href="/">Новые</a></li>
                <li><a href="/">Завершающиеся</a></li>
                <li><a href="/">Мини-проекты</a></li>
                <li><a href="/">Рекордсмены</a></li>
                <li><a href="/">Кураторы</a></li>
            </ul>

        </li>
        <li>
            <a href="/">КАТЕГОРИИ</a>
            <ul>
                <li><a href="/">Дизайн</a></li>
                <li><a href="/">Еда</a></li>
                <li><a href="/">Игры</a></li>
                <li><a href="/">Издания</a></li>
                <li><a href="/">Искусство</a></li>
                <li><a href="/">Мода</a></li>
                <li><a href="/">Музыка</a></li>
                <li><a href="/">Театр</a></li>
                <li><a href="/">Технологии</a></li>
                <li><a href="/">Фильмы и видео</a></li>
                <li><a href="/">Фотография</a></li>
                <li><a href="/">Хореография</a></li>
            </ul>

        </li>
        <li>
            <a href="/">ГОРОДА</a>
            <ul>
                <li><a href="/">Москва</a></li>
                <li><a href="/">Санкт-Петербург</a></li>
                <li><a href="/">Новосибирск</a></li>
                <li><a href="/">Волгоград</a></li>
                <li><a href="/">Краснодар</a></li>
                <li><a href="/">Нижний Новгород</a></li>
                <li><a href="/">Воронеж</a></li>
                <li><a href="/">Казань</a></li>
                <li><a href="/">Братск</a></li>
                <li><a href="/">Ростов-на-Дону</a></li>
                <li><a href="/">Уфа</a></li>
            </ul>

        </li>

    </ul>

</div>
<div class="content">

    <?php if (isset($this->exception_msg)): ?>
        <div class="alert alert-error">
            <h4 class="alert-heading">Ошибка!</h4>
            <?php echo $this->escape($this->exception_msg); ?>
        </div>
    <?php endif; ?>

    <?php if ($this->parentItem != null): ?>
        <ul class="breadcrumb">
            <li><a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'index', 'parent' => ''), $this->linkInfo->getFullUrk()); ?>"><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Гостевая книга<?php endif; ?></a> <span class="divider">/</span></li>
            <?php if ($this->parentItem->parent !== null): ?>
                <?php if ($this->parentItem->parent->parent !== null): ?>
                    <?php echo $this->partial('guest-book/_elements/public_breadcrumb.phtml', array('parentItem' => $this->parentItem->parent->parent, 'linkInfo' => $this->linkInfo)); ?>
                <?php endif; ?>
                <li><a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'index', 'parent' => $this->parentItem->parent->id), $this->linkInfo->getFullUrk() . '-parent'); ?>"><?php echo $this->escape($this->parentItem->parent->getQuestion()); ?></a> <span class="divider">/</span></li>
            <?php endif; ?>
            <li class="active"><?php echo $this->escape($this->parentItem->question); ?></li>
        </ul>
    <?php endif; ?>

    <h1><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Новости<?php endif; ?></h1>

    questionList

</div>