<legend>Контентные страницы</legend>

<a href="<?php echo $this->url(array('controller' => 'contentpage', 'action' => 'add')) ?>"><i class="icon-plus"></i>Добавить страницу</a><br/><br/>


<table class="table table-bordered">
    <tr>
        <th>Код страницы</th>
        <th>Название</th>
        <th>Действия</th>
    </tr>
    <?php if ($this->contentPageList != false): ?>
        <?php foreach ($this->contentPageList as $contentPage): ?>
        <tr>
            <td><?php echo $this->escape($contentPage->pageTitle); ?> </td>
            <td><?php echo $this->escape($contentPage->title); ?> </td>
            <td class="tedit">
                <a href="<?php echo $this->url(array('controller' => 'contentpage', 'action' => 'edit', 'title' => $contentPage->pageTitle)); ?> "><i class="icon-pencil"></a>
                <a href="<?php echo $this->url(array('controller' => 'contentpage', 'action' => 'delete', 'title' => $contentPage->pageTitle)); ?> " onclick="return confirmDelete('<?php $contentPage->title ?> ');"><i class="icon-remove"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>