<div class="right">
    <ul class="secand_menu">
        <li>
            <a href="/">ИЗБРАННОЕ</a>
            <ul>
                <li><a href="/">Рекомендуемые</a></li>
                <li><a href="/">Популярные</a></li>
                <li><a href="/">Новые</a></li>
                <li><a href="/">Завершающиеся</a></li>
                <li><a href="/">Мини-проекты</a></li>
                <li><a href="/">Рекордсмены</a></li>
                <li><a href="/">Кураторы</a></li>
            </ul>

        </li>
        <li>
            <a href="/">КАТЕГОРИИ</a>
            <ul>
                <li><a href="/">Дизайн</a></li>
                <li><a href="/">Еда</a></li>
                <li><a href="/">Игры</a></li>
                <li><a href="/">Издания</a></li>
                <li><a href="/">Искусство</a></li>
                <li><a href="/">Мода</a></li>
                <li><a href="/">Музыка</a></li>
                <li><a href="/">Театр</a></li>
                <li><a href="/">Технологии</a></li>
                <li><a href="/">Фильмы и видео</a></li>
                <li><a href="/">Фотография</a></li>
                <li><a href="/">Хореография</a></li>
            </ul>

        </li>
        <li>
            <a href="/">ГОРОДА</a>
            <ul>
                <li><a href="/">Москва</a></li>
                <li><a href="/">Санкт-Петербург</a></li>
                <li><a href="/">Новосибирск</a></li>
                <li><a href="/">Волгоград</a></li>
                <li><a href="/">Краснодар</a></li>
                <li><a href="/">Нижний Новгород</a></li>
                <li><a href="/">Воронеж</a></li>
                <li><a href="/">Казань</a></li>
                <li><a href="/">Братск</a></li>
                <li><a href="/">Ростов-на-Дону</a></li>
                <li><a href="/">Уфа</a></li>
            </ul>

        </li>

    </ul>

</div>
<div class="content">
    <h1><?php echo $this->escape($this->contentPage->title); ?></h1>

    <?php echo $this->contentPage->content ?>

</div>