<div class="right">
    <ul class="secand_menu">
        <li>
            <a href="/">ИЗБРАННОЕ</a>
            <ul>
                <li><a href="/">Рекомендуемые</a></li>
                <li><a href="/">Популярные</a></li>
                <li><a href="/">Новые</a></li>
                <li><a href="/">Завершающиеся</a></li>
                <li><a href="/">Мини-проекты</a></li>
                <li><a href="/">Рекордсмены</a></li>
                <li><a href="/">Кураторы</a></li>
            </ul>

        </li>
        <li>
            <a href="/">КАТЕГОРИИ</a>
            <ul>
                <li><a href="/">Дизайн</a></li>
                <li><a href="/">Еда</a></li>
                <li><a href="/">Игры</a></li>
                <li><a href="/">Издания</a></li>
                <li><a href="/">Искусство</a></li>
                <li><a href="/">Мода</a></li>
                <li><a href="/">Музыка</a></li>
                <li><a href="/">Театр</a></li>
                <li><a href="/">Технологии</a></li>
                <li><a href="/">Фильмы и видео</a></li>
                <li><a href="/">Фотография</a></li>
                <li><a href="/">Хореография</a></li>
            </ul>

        </li>
        <li>
            <a href="/">ГОРОДА</a>
            <ul>
                <li><a href="/">Москва</a></li>
                <li><a href="/">Санкт-Петербург</a></li>
                <li><a href="/">Новосибирск</a></li>
                <li><a href="/">Волгоград</a></li>
                <li><a href="/">Краснодар</a></li>
                <li><a href="/">Нижний Новгород</a></li>
                <li><a href="/">Воронеж</a></li>
                <li><a href="/">Казань</a></li>
                <li><a href="/">Братск</a></li>
                <li><a href="/">Ростов-на-Дону</a></li>
                <li><a href="/">Уфа</a></li>
            </ul>

        </li>

    </ul>

</div>
<div class="content">

    <h1><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Новости<?php endif; ?></h1>


    <?php if ($this->newsList !== false): ?>
        <div class="news">
            <?php foreach ($this->newsList as $item): ?>
                <div class="item">
                    <div class="img">
                        <?php if ($item->file->getName()): ?>
                            <img src="/files<?php echo $this->escape($item->file->getSubPath()); ?>/<?php echo $this->escape($item->file->getPreview()); ?>"/>
                        <?php endif; ?>
                    </div>

                    <div class="descript">
                        <p class="title"><a href="<?php echo $this->url(array('controller' => 'news', 'action' => 'viewnews', 'id' => $item->id), $this->linkInfo->link . '-viewnews') ?>"><?php echo $this->escape($item->title); ?></a></p>

                        <p class="date"><?php echo $this->escape(date('d.m.Y', strtotime($item->datePublic))); ?></p>

                        <p><?php echo $this->escape($item->shortText); ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <div class="clear"></div>
</div>