<div class="right">
    <?php echo $this->partial('news/_element/category.phtml', array('linkInfo' => $this->linkInfo, 'categoryList' => $this->categoryList)); ?>

</div>
<div class="content">

    <h1><?php echo $this->escape($this->news->title); ?></h1>

    <br/>

    <p><?php echo $this->escape(date('d.m.Y', strtotime($this->news->datePublic))); ?></p>

    <?php if ($this->news->file->getName()): ?>
        <img src="/files<?php echo $this->escape($this->news->file->getSubPath()); ?>/<?php echo $this->escape($this->news->file->getName()); ?>"/>
    <?php endif; ?>

    <p><?php echo $this->news->fullText; ?></p>


    <div class="clear"></div>
</div>