<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <title>ИТР</title>

    <script type="text/javascript" language="javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" language="javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" language="javascript" src="/js/i18n/jquery.ui.datepicker-ru.js"></script>
    <script type="text/javascript" src="/js/jquery.jcarousel.min.js"></script>
    <script type="text/javascript" src="/js/jquery.timers.js"></script>
    <script type="text/javascript" src="/js/jquery.datepick.js"></script>
    <script type="text/javascript" src="/js/jquery.mousewheel.js"></script>
    <script type="text/javascript" src="/js/jquery.jscrollpane.js"></script>
    <script type="text/javascript" src="/js/modernizr.min.js"></script>
    <!-- <script type="text/javascript" language="javascript" src="/js/bootstrap.min.js"></script> -->

    <script src="/js/scripts.js" type="text/javascript"></script>

    <link rel="stylesheet" type="text/css" href="/css/jquery-ui.css"/>
    <link rel="stylesheet" type="text/css" href="/css/jquery.datepick.css"/>
    <link rel="stylesheet" type="text/css" href="/css/jquery.jscrollpane.css"/>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="/css/styles.css"/>

    <script type="text/javascript">
        $(function () {
            $('#inlineDatepicker').datepick({onSelect: showDate});
        });

        function showDate(date) {
            alert('Вывод ' + date);// тут нужно вставить функцию аякс запроса
        }

        jQuery(function () {
            jQuery('.projects_from_cal').jScrollPane();
        });
    </script>
    <!--[if lte IE 6]>
    <script src="/js/png.js"></script>
    <script>DD_belatedPNG.fix('div, a, img, span');</script>
    <![endif]-->
    <!--[if !IE 7]>
    <style type="text/css">
        #wrap {
            display: table;
            height: 100%
        }
    </style>
    <![endif]-->

    <!--[if lt IE 9]>
    <script>
        var e = ("abbr,article,aside,audio,canvas,datalist,details," +
            "figure,footer,header,hgroup,mark,menu,meter,nav,output," +
            "progress,section,time,video").split(',');
        for (var i = 0; i < e.length; i++) {
            document.createElement(e[i]);
        }
    </script>
    <![endif]-->
    <script>
        jQuery(document).ready(function () {

            $('.cal_nav .prev').click(function () {
                alert('По клику по видимому аякс запрос надо поставить на обновление списка ');
            });
            $('.cal_nav .next').click(function () {
                alert('По клику по видимому аякс запрос надо поставить на обновление списка ');
            });

            jQuery('#partners_carousel').jcarousel({

            });
            jQuery('#popular_projects_carousel').jcarousel({

            });
        });
    </script>


</head>
<body>

<header class="header">
    <div class="center">
        <div class="admin_menu_link">
            <?php if ($this->authUserRole !== 'guest'): ?>
                <a href="/menu/" class="uppercase">Управление разделами</a> /
                <a href="/banner/" class="uppercase">Баннеры</a> /
                <a href="/phone/" class="uppercase">Телефоны</a> /
            <?php endif; ?>
        </div>
        <div class="account_link"><?php if ($this->authUserRole !== 'guest'): ?><a href="/login/logout/" class="uppercase"><?php echo $this->authUser; ?> (выход)</a><?php else: ?><a href="/login/">Вход</a><?php endif; ?></div>
        <div class="social">
            <ul>
                <li>
                    <noindex><a class="vk" href="http://vkontakte.ru/share.php?url=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>
                <li>
                    <noindex><a class="odn" rel="nofollow" target="_blank" href="http://www.odnoklassniki.ru/dk?st.cmd=addShare&amp;st.s=1&amp;st._surl=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>"></a></noindex>
                </li>
                <li>
                    <noindex><a class="mail" href="http://connect.mail.ru/share?share_url=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>
                <li>
                    <noindex><a class="tw" href="http://twitter.com/home?status=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>
                <li>
                    <noindex><a class="fbook" href="http://www.facebook.com/sharer.php?u=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>


            </ul>
        </div>

        <div class="logo"><a href="/"></a></div>

        <nav>
            <ul>
                <?php $firstItem = true; ?>
                <?php foreach ($this->topMenuList as $item): ?>
                    <li <?php if ($firstItem): $firstItem = false; ?>class="first"<?php endif; ?> >
                        <a href="<?php echo $this->escape($item->getUrl($this->authUserRole)); ?>"><?php echo $this->escape($item->title) ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>

        <div class="search">
            <form action="/search/index/" method="post">
                <input type="text" name="query" class="search_field" value=""/>
                <input type="submit" name="submit_search" class="search_button" value=""/>
            </form>
        </div>

        <div class="ed_project">
            <a href="/" class="add_project">Добавить Проект</a>
            <a href="/" class="dev_project">Развить Проект</a>
        </div>

    </div>
</header>

<?php if ($this->authUserRole !== 'guest'): ?>
    <div class="page">
        <?php echo $this->layout()->content; ?>
    </div>
<?php else: ?>
    <?php if ($this->controller == 'index'): ?>
        <?php echo $this->layout()->content; ?>
    <?php else: ?>
        <div class="page">
            <?php echo $this->layout()->content; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>

<!--футер-->
<div class="pad"></div>
<footer>
    <div class="footer_center">
        <div class="copyr">
            <p>&copy; <?php echo date('Y'); ?> ООО "РС-Групп" г.Кемерово</p>

            <p><?php echo $this->escape($this->mainPhone->phone); ?></p>

            <p><?php echo $this->escape($this->mainPhone->postIndex); ?>. <?php echo $this->mainPhone->address; ?></p>
        </div>
        <div class="social">
            <ul>
                <li>
                    <noindex><a class="vk" href="http://vkontakte.ru/share.php?url=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>
                <li>
                    <noindex><a class="odn" rel="nofollow" target="_blank" href="http://www.odnoklassniki.ru/dk?st.cmd=addShare&amp;st.s=1&amp;st._surl=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>"></a></noindex>
                </li>
                <li>
                    <noindex><a class="mail" href="http://connect.mail.ru/share?share_url=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>
                <li>
                    <noindex><a class="tw" href="http://twitter.com/home?status=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>
                <li>
                    <noindex><a class="fbook" href="http://www.facebook.com/sharer.php?u=http://<?= $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>" rel="nofollow" target="_blank"></a></noindex>
                </li>


            </ul>
        </div>
    </div>
</footer>

</body>
</html>