<legend>Справочники для проектов</legend>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">

            <h3>Справочники</h3>

            <div class="well" style="padding: 8px 0;">
                <ul class="nav nav-list">
                    <li class="active">
                        <a href="/project-branch/index/">Отрасли</a>
                        <a href="/project-handbook/index/">Направления</a>
                        <a href="/project-handbook/index/">Стадии</a>
                        <a href="/project-handbook/index/">Что требуется</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="span9">

            <h3>Справочник</h3>

        </div>
    </div>
</div>