<legend>Справочники для проектов</legend>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">

            <h3>Справочники</h3>

            <div class="well" style="padding: 8px 0;">
                <ul class="nav nav-list">
                    <li <?php if ($this->currentHandbook == 'branch'): ?>class="active"<?php endif; ?>>
                        <a href="/project-handbook/index/handbook/branch/" onclick="changeHandbook('#handbookContent', 'branch', this); return false;">Отрасли</a>
                    </li>
                    <li <?php if ($this->currentHandbook == 'direction'): ?>class="active"<?php endif; ?>>
                        <a href="/project-handbook/index/handbook/direction/" onclick="changeHandbook('#handbookContent', 'direction', this); return false;">Направления</a>
                    </li>
                    <li <?php if ($this->currentHandbook == 'stage'): ?>class="active"<?php endif; ?>>
                        <a href="/project-handbook/index/handbook/stage/" onclick="changeHandbook('#handbookContent', 'stage', this); return false;">Стадии</a>
                    </li>
                    <li <?php if ($this->currentHandbook == 'requirements'): ?>class="active"<?php endif; ?>>
                        <a href="/project-handbook/index/handbook/requirements/" onclick="changeHandbook('#handbookContent', 'requirements', this); return false;">Что требуется</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="span9" id="handbookContent">

            <h3>Справочник</h3>

        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        changeHandbook('#handbookContent', '<?php echo $this->currentHandbook; ?>', null);
    });
</script>