<legend>Добавить проект</legend>

<form class="form-horizontal" action="<?php echo $this->url(array('controller' => 'project', 'action' => 'register')); ?>">

    <div class="control-group">
        <label class="control-label">Название проекта</label>

        <div class="controls">
            <input type="text" name="data[title]" value="<?php echo $this->escape($this->project->title); ?>"/>
            <span class="help-inline hide">Заполните поле</span>

            <p class="help-block">(до 30 символов с пробелами)</p>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Вы - компания?</label>

        <div class="controls">
            <input type="checkbox" name="data[is_company]" <?php if ($this->project->isCompany == true): ?>checked="checked"<?php endif; ?> />
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>

    <div id="companyBlock">
        <div class="control-group">
            <label class="control-label">Название комании</label>

            <div class="controls">
                <input type="text" name="data[company_title]" value="<?php echo $this->escape($this->project->companyTitle); ?>"/>
                <span class="help-inline hide">Заполните поле</span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Ф.И.О. контактного лица</label>

            <div class="controls">
                <input type="text" name="data[company_contact_fio]" value="<?php echo $this->escape($this->project->companyContactFio); ?>"/>
                <span class="help-inline hide">Заполните поле</span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">E-mail</label>

            <div class="controls">
                <input type="text" name="data[company_contact_email]" value="<?php echo $this->escape($this->project->companyContactEmail); ?>"/>
                <span class="help-inline hide">Заполните поле</span>
            </div>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Описание проекта</label>

        <div class="controls">
            <textarea name="data[description]"><?php echo $this->escape($this->project->description); ?></textarea>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Вид результирующей продукции (или технологии) проекта</label>

        <div class="controls">
            <textarea name="data[resulting_products]"><?php echo $this->escape($this->project->resultingProducts); ?></textarea>
            <span class="help-inline hide">Заполните поле</span>

            <p class="help-block">(до 200 символов с пробелами)</p>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Базовые функции (по возможности не более 5)</label>

        <div class="controls">
            <textarea name="data[basic_function]"><?php echo $this->escape($this->project->basicFunction); ?></textarea>
            <span class="help-inline hide">Заполните поле</span>

            <p class="help-block">(до 200 символов с пробелами)</p>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Дополнительные функции</label>

        <div class="controls">
            <textarea name="data[additional_features]"><?php echo $this->escape($this->project->additionalFeatures); ?></textarea>
            <span class="help-inline hide">Заполните поле</span>

            <p class="help-block">(до 500 символов с пробелами)</p>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Потенциальные потребители</label>

        <div class="controls">
            <textarea name="data[potential_customers]"><?php echo $this->escape($this->project->potentialCustomers); ?></textarea>
            <span class="help-inline hide">Заполните поле</span>

            <p class="help-block">(до 500 символов с пробелами)</p>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Существующие аналоги (перечислите и укажите ваши основные отличия)</label>

        <div class="controls">
            <textarea name="data[analogs]"><?php echo $this->escape($this->project->analogs); ?></textarea>
            <span class="help-inline hide">Заполните поле</span>

            <p class="help-block">(до 1000 символов с пробелами)</p>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Отрасль</label>

        <div class="controls">
            <select name="data[branch]">
                <option value="">-- Выберите отрасль</option>
                <?php if ($this->branchList): ?>
                    <?php foreach ($this->branchList as $branch): ?>
                        <option value="<?php echo $this->escape($branch->id); ?>" <?php if ($this->project->branch !== null && $this->project->branch->id == $branch->id): ?>selected="selected"<?php endif; ?> ><?php echo $this->escape($branch->title); ?></option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Направление</label>

        <div class="controls">
            <select name="data[direction]">
                <option value="">-- Выберите направление</option>

            </select>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Стадия проекта</label>

        <div class="controls">
            <select name="data[stage]">
                <option value="">-- Выберите стадию проекта</option>
                <?php if ($this->stageList): ?>
                    <?php foreach ($this->stageList as $stage): ?>
                        <option value="<?php echo $this->escape($stage->id); ?>" <?php if ($this->project->stage !== null && $this->project->stage->id == $stage->id): ?>selected="selected"<?php endif; ?> ><?php echo $this->escape($stage->title); ?></option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Надо для завершения</label>

        <div class="controls">
            <select name="data[requirements]">
                <option value="">-- Выберите что надо для завершения</option>
                <?php if ($this->requirementsList): ?>
                    <?php foreach ($this->requirementsList as $requirements): ?>
                        <option value="<?php echo $this->escape($requirements->id); ?>" <?php if ($this->project->requirements !== null && $this->project->requirements->id == $requirements->id): ?>selected="selected"<?php endif; ?> ><?php echo $this->escape($requirements->title); ?></option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Сколько нужно для завершения</label>

        <div class="controls">
            <textarea name="data[requirements_text]"><?php echo $this->escape($this->project->requirementsText); ?></textarea>
            <span class="help-inline hide">Заполните поле</span>

            <p class="help-block">(до 1000 символов с пробелами)</p>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Введите код с картинки</label>

        <div class="controls">
            <img src="/kcaptcha/?<?php echo session_name() . '=' . session_id(); ?>">
            <input type="text" name="data[capthe]" value="" class="input-mini"/>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>

    <div class="form-actions">
        <input type="submit" class="btn btn-success" value="Сохранить"/>
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>" class="btn btn-danger">Отмена</a>
    </div>
</form>