<div class="page_project">
    <div class="page_project_inner">
        <div class="nav">Проекты / <a href="/project/index/branchId/<?php echo $this->escape($this->project->branch->id); ?>/"><?php echo $this->escape($this->project->branch->title); ?></a></div>

        <h1><?php echo $this->escape($this->project->title); ?></h1>

        <div class="project_content">
            <div class="project_menu">
                <ul>
                    <li><a href="/project/view/id/<?php echo $this->escape($this->project->id); ?>" class="selected">Меню проекта</a></li>
                    <li><a href="/project/view/id/<?php echo $this->escape($this->project->id); ?>">Спонсоры</a></li>
                    <li><a href="/project/view/id/<?php echo $this->escape($this->project->id); ?>">Обновления</a></li>
                    <li><a href="/project/view/id/<?php echo $this->escape($this->project->id); ?>">Последние комментарии</a></li>
                </ul>
                <div class="clear"></div>
            </div>

            <div class="project_right_content">
                <?php if ($this->project->isCompany): ?>
                    <p>Компания: <?php echo $this->escape($this->project->companyTitle); ?></p>
                    <p>Ф.И.О. контактного лица: <?php echo $this->escape($this->project->companyContactFio); ?></p>
                    <p>Контактный телефон: <?php echo $this->escape($this->project->companyContactPhone); ?></p>
                    <p>E-mail: <?php echo $this->escape($this->project->companyContactEmail); ?></p>
                    <br/><br/>
                <?php endif; ?>

                <p>Направление: <?php echo $this->escape($this->project->direction->title); ?></p><br/>
                <p>Стадия: <?php echo $this->escape($this->project->stage->title); ?></p><br/>
                <p>Что требуется?: <?php echo $this->escape($this->project->requirement->title); ?></p><br/>
                <p>Сколько требуется?: <?php echo $this->escape($this->project->requirementsText); ?></p>
            </div>

            <div class="project_left_content">
                <?php if ($this->project->img->getName()): ?>
                    <img src="/projects/<?php echo $this->project->img->getPreview(); ?>" border="0"/>
                    <br/><br/>
                <?php endif; ?>

                <p><?php echo $this->escape($this->project->description); ?></p>

                <br/>

                <p><?php echo $this->escape($this->project->resultingProducts); ?></p>

                <br/>

                <p><?php echo $this->escape($this->project->basicFunction); ?></p>

                <br/>

                <p><?php echo $this->escape($this->project->additionalFeatures); ?></p>

                <br/>

                <p><?php echo $this->escape($this->project->potentialCustomers); ?></p>

                <br/>

                <p><?php echo $this->escape($this->project->analogs); ?></p>
            </div>


        </div>


        <a class="all_projects" href="/project/index/">Все проекты >></a>

    </div>
</div>